# Generated by Django 3.2.6 on 2021-12-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='porblem',
            new_name='problem',
        ),
    ]
