# Generated by Django 3.2.6 on 2021-12-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_porblem_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='problem',
            name='examples',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='problem',
            name='inputs',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='problem',
            name='outputs',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=1000, null='true'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(null='true'),
        ),
    ]
