# Generated by Django 3.2.6 on 2021-12-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211206_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.problem')),
            ],
        ),
        migrations.CreateModel(
            name='solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=100)),
                ('prob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.problem')),
            ],
        ),
    ]
