# Generated by Django 3.2.6 on 2021-12-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211206_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveinput', models.TextField()),
                ('expectedoutput', models.TextField()),
                ('prob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.problem')),
            ],
        ),
        migrations.DeleteModel(
            name='testcase',
        ),
    ]
