# Generated by Django 3.2.6 on 2021-12-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20211206_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='index',
        ),
    ]
