# Generated by Django 3.2.6 on 2021-12-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_problem_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='code',
        ),
        migrations.AddField(
            model_name='solutions',
            name='code',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
    ]
