# Generated by Django 3.2.6 on 2021-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_solutions_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='code',
        ),
    ]
