# Generated by Django 3.2.6 on 2021-12-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20211208_0110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='codeit',
        ),
    ]
