# Generated by Django 3.2.6 on 2021-12-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_codeit_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='codeit',
        ),
        migrations.AddField(
            model_name='solutions',
            name='code',
            field=models.TextField(blank='true'),
        ),
    ]
