# Generated by Django 3.2.6 on 2021-12-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20211208_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='code',
        ),
        migrations.AddField(
            model_name='solutions',
            name='code',
            field=models.TextField(blank='true'),
        ),
    ]
