# Generated by Django 3.2.6 on 2021-12-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20211208_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='verdict',
            field=models.CharField(blank='true', max_length=100),
        ),
    ]
