# Generated by Django 3.2.6 on 2021-12-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_solutions_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='out',
            field=models.FileField(max_length=250, null='true', upload_to=''),
            preserve_default='true',
        ),
    ]
