# Generated by Django 3.2.6 on 2021-12-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_test_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='out',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='test',
            name='expectedoutput',
        ),
        migrations.RemoveField(
            model_name='test',
            name='giveinput',
        ),
        migrations.AddField(
            model_name='test',
            name='op',
            field=models.FileField(max_length=250, null='true', upload_to=''),
            preserve_default='true',
        ),
    ]
