# Generated by Django 3.2.6 on 2021-12-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20211211_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='inp',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='test',
            name='oup',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
    ]
