# Generated by Django 3.2.6 on 2021-12-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20211211_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='verdict',
            field=models.CharField(blank='true', default='null', max_length=100),
        ),
    ]
