# Generated by Django 3.2.6 on 2021-12-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_solutions_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='verdict',
            field=models.CharField(blank='true', default='ok', max_length=100),
        ),
    ]
