# Generated by Django 3.2.6 on 2021-12-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_test_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.TextField(blank='true', default='true'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='verdict',
            field=models.CharField(blank='true', default='true', max_length=100),
        ),
    ]
