# Generated by Django 3.2.6 on 2021-12-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20211212_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='verdict',
            field=models.IntegerField(blank='true'),
        ),
    ]
