# Generated by Django 3.2.6 on 2021-12-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='verdict',
            field=models.IntegerField(null='true'),
        ),
    ]
